---
title: "EED-Development Tables"
subtitle: "WASH Benefits, Bangladesh" 
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
  pdf_document: 
  html_notebook:
    theme: sandstone
classoption: landscape
geometry: margin=0.5in
---

```{r setup, include = F}
library(tidyverse)
library(kableExtra)
```



```{r}
bg_tables <- readRDS('tables/all_bangladesh_tables.RDS')
k_tables <- readRDS('tables/all_kenya_tables.RDS')

```



```{r}
every_hyp <- bind_rows(
  bg_tables, 
  k_tables
) 


every_hyp %>% 
  arrange(hyp) %>%
  kable(booktabs = TRUE) %>% 
  kable_styling(latex_options="scale_down")
```

Significant Hypotheses

```{r}
sig_hyp <- every_hyp %>% 
  filter(`Unadjusted P-value` <= 0.05 | `Adjusted P-value` <= 0.05 | `FDR Corrected P-value` <= 0.05 ) %>% 
  mutate(significant_unadj = ifelse(`Unadjusted P-value` <= 0.05, "Unadj.", NA), 
         significant_adj = ifelse(`Adjusted P-value` <= 0.05, 'Adj.', NA), 
         significant_fdr = ifelse(`FDR Corrected P-value` <= 0.05, 'FDR', NA), 
         dir = case_when(str_starts(`Adjusted Difference (95% CI)`, 
                                    '-') ~ '-', 
                         str_detect(`Adjusted Difference (95% CI)`, 
                                    "0,0") ~ "", 
                         TRUE ~ '+')) %>% 
  unite("signif", significant_unadj, significant_adj, significant_fdr, sep = ', ', na.rm = TRUE)  %>% 
  select(`Outcome Domain`, Outcome, Exposure, n, t, `Adjusted Difference (95% CI)`,	`Unadj. P-value` = `Unadjusted P-value`,
         `Adj. P-value` = `Adjusted P-value`, `FDR P-value` = `FDR Corrected P-value`, hyp, signif, dir)
```

Long Tables

```{r}
sig_hyp %>% 
  filter(hyp <= 3) %>% 
  kable(booktabs = TRUE, longtable = TRUE, 
        caption = 'Any Significant p-value (Bangladesh)') %>% 
  kable_styling(latex_options=c("hold_position", "repeat_header"), font_size = 7)

sig_hyp %>% 
  filter(hyp > 3) %>% 
  kable(booktabs = TRUE, longtable = TRUE, 
        caption = 'Any Significant p-value (Kenya)') %>% 
  kable_styling(latex_options=c("hold_position", "repeat_header"), font_size = 7)
```

Tables Arranged

```{r}
sig_hyp %>% 
  arrange(`Outcome Domain`, Outcome) %>% 
  kable(booktabs = TRUE, 
        caption = "By Outcome") %>% 
  kable_styling(latex_options="scale_down")

sig_hyp %>% 
  arrange(Exposure) %>% 
  kable(booktabs = TRUE, 
        caption = 'By Exposure') %>% 
  kable_styling(latex_options="scale_down")
```
```{r}
sig_hyp %>% 
  filter(signif != "Unadj.") %>% 
  arrange(hyp, Exposure) %>% 
  kable(booktabs = TRUE, 
        caption = 'Only Significant Adj/FDR Corrected' ) %>% 
  kable_styling(latex_options="scale_down")
```

