---
title: "EED-Development Tables"
subtitle: "WASH Benefits - Kenya" 
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
  html_notebook:
    theme: sandstone
---

```{r setup, include = F}

rm(list=ls())
library("xtable")
source(here::here("0-config.R"))

adj_mods <- dir(here('results/adjusted'))
unadj_mods <- dir(here('results/unadjusted/'))

# create df of exposure names
# to merge actual names
exp_rename <- tribble(
  ~var,     ~exposure,       ~exp_domain,
  'aat',   'Alpha-1 Antitrypsin', 'fecal',
  'mpo',   'Myeloperoxidase',      'fecal', 
  'neo',   'Neopterin',            'fecal', 
  'Lact', 'Lactulose concentration', 'urine', 
  'Mann', 'Mannitol concentration', 'urine',
  'reg1b', 'Regenerating Gene 1-Beta', 'fecal'
)

# create df of outcome names
# to merge in 
outcome_rename <- tribble(
  ~var,            ~outcome,  ~outcome_domain,
  'who_sum_total', 'Sum Total', 'WHO Motor Milestone', 
  'who_sub_total', 'Milestones 2, 4, 5, 6', 'WHO Motor Milestone', 
  'personal', 'Personal Social Score', 'Extended Ages and Stages Questionnaire', 
  'motor', 'Gross Motor Score', 'Extended Ages and Stages Questionnaire', 
  'combined', 'Combined', 'Extended Ages and Stages Questionnaire', 
  'communication', 'Communication Score', 'Extended Ages and Stages Questionnaire', 
  'cdi_und', 'Understanding', 'Communicative Development Inventories', 
  'cdi_say', 'Expressing' , 'Communicative Development Inventories'
)


```

## Hypothesis 4

```{r h4_setup, include = F}
# read in data
h4_adj <- readRDS(here('results/adjusted/H4_all_adj_res.RDS')) %>% 
  mutate_if(is.numeric, round, 2)
h4_unadj <- readRDS(here('results/unadjusted/H4_res.RDS'))%>% 
  mutate_if(is.numeric, round, 2)


all_h4 <- h4_adj %>% 
  left_join(h4_unadj, 
            by = c('X', 'Y'), 
            suffix = c('_adj', '_unadj')) %>% 
  mutate(X = str_remove(X, '[0-9]'), 
         Y = case_when(str_detect(Y, 'comtotz') ~ 'communication',
                       str_detect(Y, 'mottotz') ~ 'motor',
                       str_detect(Y, 'pstotz') ~ 'personal',
                       str_detect(Y, 'global') ~ 'combined',
                       TRUE ~ Y)) %>% 
  left_join(exp_rename, 
            by = c('X' = 'var')) %>% 
  left_join(outcome_rename, 
            by = c('Y' = 'var'))

# use adjusted values except for unadjust CI and pval
```

### Full Table 2

```{r echo = F}
h4_table <- data.table(
  "Outcome Domain" = all_h4$outcome_domain,
  "Outcome" = all_h4$outcome,
  "Exposure Source" = all_h4$exp_domain,
  "Exposure" = all_h4$exposure, 
  "n" = all_h4$N_adj, # uses N from adjusted model
  "Q1 mean" = all_h4$q1_adj,
  "Q3 mean" = all_h4$q3_adj,
  "Unadjusted Difference (95% CI)" = paste0(all_h4$point.diff_unadj, "(", all_h4$lb.diff_unadj, ',', all_h4$ub.diff_unadj,')'), 
  "Unadjusted P-value" = all_h4$Pval_unadj,
  "Adjusted Difference (95% CI)" = paste0(all_h4$point.diff_adj, "(", all_h4$lb.diff_adj, ',', all_h4$ub.diff_adj,')'), 
  "Adjusted P-value" = all_h4$Pval_adj, 
  "FDR Corrected P-value" = all_h4$corrected.Pval_adj
)

h4_table
```

### By Outcome Domain

#### WHO Motor Milestone

```{r}
# sort(unique(h1_table$`Outcome Domain`))
h4_who <- h4_table %>% 
  filter(`Outcome Domain` == "WHO Motor Milestone") %>%
  arrange(`Exposure Source`, Exposure, `Outcome Domain`, Outcome) %>% 
  group_by(`Exposure Source`, `Outcome Domain`) %>%
  mutate(`Outcome Domain` = case_when(row_number() == 1 ~ `Outcome Domain`), 
         `Exposure Source` = case_when(row_number() == 1 ~ `Exposure Source`)) %>% 
  ungroup() %>% 
  select(-`Exposure Source`) %>% 
  tibble()

h4_who
```

```{r}
#save table
write.csv(h4_who, file=here('tables/eed-dev_h4-who.csv'))
print(xtable(h4_who), type="html", file=here("tables/eed-dev_h4-who.html"))
```

## Hypothesis 5

```{r h5_setup, include = F}
# read in data
h5_adj <- readRDS(here('results/adjusted/h5_all_adj_res.RDS')) %>% 
  mutate_if(is.numeric, round, 2)
h5_unadj <- readRDS(here('results/unadjusted/h5_res.RDS'))%>% 
  mutate_if(is.numeric, round, 2)


all_h5 <- h5_adj %>% 
  left_join(h5_unadj, 
            by = c('X', 'Y'), 
            suffix = c('_adj', '_unadj')) %>% 
  mutate(X = str_remove(X, '[0-9]'), 
         Y = case_when(str_detect(Y, 'comtotz') ~ 'communication',
                       str_detect(Y, 'mottotz') ~ 'motor',
                       str_detect(Y, 'pstotz') ~ 'personal',
                       str_detect(Y, 'global') ~ 'combined',
                       TRUE ~ Y)) %>% 
  left_join(exp_rename, 
            by = c('X' = 'var')) %>% 
  left_join(outcome_rename, 
            by = c('Y' = 'var'))

# use adjusted values except for unadjust CI and pval
```

### Full Table 3

```{r echo = F}
h5_table <- data.table(
  "Outcome Domain" = all_h5$outcome_domain,
  "Outcome" = all_h5$outcome,
  "Exposure Source" = all_h5$exp_domain,
  "Exposure" = all_h5$exposure, 
  "n" = all_h5$N_adj, # uses N from adjusted model
  "Q1 mean" = all_h5$q1_adj,
  "Q3 mean" = all_h5$q3_adj,
  "Unadjusted Difference (95% CI)" = paste0(all_h5$point.diff_unadj, "(", all_h5$lb.diff_unadj, ',', all_h5$ub.diff_unadj,')'), 
  "Unadjusted P-value" = all_h5$Pval_unadj,
  "Adjusted Difference (95% CI)" = paste0(all_h5$point.diff_adj, "(", all_h5$lb.diff_adj, ',', all_h5$ub.diff_adj,')'), 
  "Adjusted P-value" = all_h5$Pval_adj, 
  "FDR Corrected P-value" = all_h5$corrected.Pval_adj
)

h5_table
```

### By Outcome Domain

#### Extended Ages and Stages Questionnaire

```{r}
# sort(unique(h4_table$`Outcome Domain`))
h5_easq <- h5_table %>% 
  filter(`Outcome Domain` == "Extended Ages and Stages Questionnaire") %>%
  arrange(`Exposure Source`, Exposure, `Outcome Domain`, Outcome) %>% 
  group_by(`Exposure Source`, `Outcome Domain`) %>%
  mutate(`Outcome Domain` = case_when(row_number() == 1 ~ `Outcome Domain`), 
         `Exposure Source` = case_when(row_number() == 1 ~ `Exposure Source`)) %>% 
  ungroup() %>% 
  select(-`Exposure Source`) %>% 
  tibble()

h5_easq
```


```{r}
#save table
write.csv(h5_easq, file=here('tables/eed-dev_h5-who.csv'))
print(xtable(h5_easq), type="html", file=here("tables/eed-dev_h5-easq.html"))
```


## Significant Hypotheses

All analyses in one table. 

```{r}
all_hyp <- bind_rows(
  h4_table %>% 
    mutate(hyp = 4), 
  h5_table %>% 
    mutate(hyp = 5)
) 

all_hyp
```

```{r}
saveRDS(all_hyp, 'all_kenya_tables.RDS')
```


```{r}
all_hyp %>% 
  filter(`Adjusted P-value` < 0.06) # rounding
```

Random Aggregations 

```{r}
all_hyp %>% 
  group_by(`Exposure Source`) %>% 
  mutate(direction = case_when(str_starts(`Adjusted Difference (95% CI)`, 
                                          '-') ~ '-', TRUE ~ '+')) %>% 
  count(direction)
```

```{r}
all_hyp %>% 
  group_by(hyp) %>% 
  mutate(direction = case_when(str_starts(`Adjusted Difference (95% CI)`, 
                                          '-') ~ '-', TRUE ~ '+')) %>% 
  count(direction)
```

